-- Run this in the Supabase SQL Editor

-- 1. Create Messages Table
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  subject text,
  message text
);

-- 2. Create Projects Table
create table projects (
  id bigint generated by default as identity primary key,
  title text,
  category text, -- 'built' or 'digital'
  image_url text,
  description text
);

-- 3. Enable Security (Start Public for demo)
alter table messages enable row level security;
alter table projects enable row level security;

create policy "Enable insert for all users" on messages for insert with check (true);
create policy "Enable read for all users" on projects for select using (true);
create policy "Enable insert for all users" on projects for insert with check (true); 

-- 4. Create Quote Requests Table
create table quote_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  phone text,
  service_type text,
  message text
);

-- 5. Enable Security for Quotes
alter table quote_requests enable row level security;
create policy "Enable insert for all users" on quote_requests for insert with check (true);

-- 6. Grant Admin Access (Authenticated Users Only)
-- These separate policies allow logged-in users (Admins) to VIEW the data.
-- Currently, public users can only INSERT (Send), but not VIEW.
create policy "Enable read for authenticated users only" on messages for select to authenticated using (true);
create policy "Enable read for authenticated users only" on quote_requests for select to authenticated using (true); 

-- 4. Initial seed data (Optional - run this to get some data in immediately)
insert into projects (title, category, image_url, description) values
('Modern Residence', 'built', 'img/b1.jpeg', 'This project is a modern 4-bedroom residential design on a 50ft x 70ft plot.'),
('Brand Identity', 'digital', 'img/b2.jpeg', 'Branding and logo design for client by itisus Digital.'),
('Commercial Complex', 'built', 'img/b3.jpeg', 'Commercial building design project by itisus Built.'),
('3D Visualization', 'digital', 'img/b4.jpeg', '3D modeling and rendering project by itisus Digital.');
